### ISSUE TITLE
Cannot connect to sessions on Authenticate

### ISSUE THREAD

**Issue by 2dvisio** [arangodb/user-service#1]
When accessing the /{userId}/authenticate the Session creation fails.
The error has the following stacktrace:

```
{
  "exception": "NotFoundError: Not Found",
  "stacktrace": [
    "NotFoundError: Not Found",
    "    at Object.createSession [as create] (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/var/lib/arangodb-apps/_db/smwt/users/APP/sessions.js:38:11)",
    "    at /Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/sessions.js:80:30",
    "    at callback (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/controller.js:608:24)",
    "    at execute (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
    "    at next (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
    "    at BaseMiddleware.middleware (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)",
    "    at execute (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)",
    "    at next (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1326:7)",
    "    at BaseMiddleware.middleware (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/foxx/base_middleware.js:424:5)",
    "    at execute (/Applications/ArangoDB-CLI.app/Contents/MacOS/opt/arangodb/share/arangodb/js/server/modules/org/arangodb/actions.js:1309:7)"
  ],
  "error": true,
  "code": 404,
  "errorNum": 404,
  "errorMessage": "failed to execute foxx mounted at '/users'"
}
```

We have configured this [session service](https://github.com/arangodb-foxx/service-sessions) and we verified that it works on its own (with the POST on /).

The error we get in the sessions.js:38:11 corresponds to this response from the /sessions API:

```
  if (res.status >= 400) {
    throw new httperr[res.status](res.message);
  }
```

Am I missing something?
Do you have any guide / tutorial?

**Comment by pluma** [comment]
The error indicates that the session service itself returned a 404.

Are you sure that the users service is configured correctly, specifically that the `sessionsRoot` setting corresponds to the full public URL (or the mount point in case it is running locally) of the `sessions` service?

**Comment by 2dvisio** [comment]
Hello @pluma,

The sessionsRoot points to `/sessions` and on that mount point we have installed the ArangoDB Session-Service.
